name: mainline-release-pgo-build
# on: workflow_dispatch
on: push

jobs:
  tag:
    runs-on: "ubuntu-latest"
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
      tag: ${{ steps.generate-tag.outputs.tag }}
      sha: ${{ steps.generate-sha.outputs.sha }}
    steps:
    - id: generate-version
      run: echo version=v2.0.0 >> "$GITHUB_OUTPUT"
    - run: git clone --depth 1 https://gitlab.com/AOMediaCodec/SVT-AV1.git --branch ${{ steps.generate-version.outputs.version }} --single-branch .
    - id: generate-tag
      run: echo tag=pgo-build-$(git log -1 "--date=format:%F" "--format=%ad-%h") >> "$GITHUB_OUTPUT"
    - id: generate-sha
      run: echo sha=$(git log -1 "--format=%H") >> "$GITHUB_OUTPUT"


  release:
    needs: tag
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v7
    - run: GH_TOKEN=${{ github.token }} gh release delete ${{ needs.tag.outputs.tag }} --cleanup-tag
      continue-on-error: true
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        target_commitish: pgo-build-tags
        name: Mainline SVT-AV1 ${{ needs.tag.outputs.version }}
        body: |
          Release `${{ needs.tag.outputs.version }}` | Commit `${{ needs.tag.outputs.sha }}`  
          Windows | x86-64 | LLVM Project Clang LLD | winthread | `icelake-server` + `znver5` | LTO PGO  
          Windows | x86-64 | LLVM Project Clang LLD | winthread | `znver2` | LTO PGO  
          Windows | x86-64 | LLVM Project Clang LLD | winthread | `x86-64-v3` + `znver2` | LTO PGO  
          Windows | arm64 | LLVM Project Clang LLD | winthread | `armv8.7-a+crypto+sm4+sha3+fp16+sve+sve2` + `oryon-1` | LTO PGO  
          Linux | x86-64 | LLVM Project Clang LLD | `icelake-server` + `znver5` | LTO PGO  
          Linux | x86-64 | LLVM Project Clang LLD | `znver2` | LTO PGO  
          Linux | x86-64 | LLVM Project Clang LLD | `x86-64-v3` + `znver2` | LTO PGO  
          macOS | arm64 | LLVM Project Clang LLD | `armv8.5-a+simd+crypto` + `apple-m3` | LTO PGO  
          macOS | x86-64 | LLVM Project Clang LLD | `skylake` | LTO PGO  

          These builds are provided for archival purpose. Check our [README](../../../#svt-av1-builds) for latest recommendations.  

          Thanks to studies and contributions from afed, Emre, Ironclad, Itachi Uchiha, Khaoklong, Miss Ashenlight, Soda, SwareJonge, Trix, Yiss, and other people in the community for discovering the method to build the fastest binary.  
        prerelease: false
        make_latest: "false"


  build-windows-x86-64:
    needs: [tag, release]
    runs-on: "windows-latest"
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - run: git clone https://gitlab.com/AOMediaCodec/SVT-AV1.git --branch ${{ needs.tag.outputs.version }} --single-branch .
      shell: pwsh

    - uses: Akatmks/build-svt-av1@v1
      with:
        dovi-hdr10plus: "false"
        cmakeflags: "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

    - id: detect-icelake-server-znver5
      run: ls BuildAction/icelake-server+znver5/static/SvtAv1EncApp.exe
      continue-on-error: true
    - run: cd BuildAction/icelake-server+znver5/static && tar cJf Windows_x86-64_icelake-server+znver5.tar.xz SvtAv1EncApp.exe
      if: ${{ steps.detect-icelake-server-znver5.outcome != 'failure' }}
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: BuildAction/icelake-server+znver5/static/Windows_x86-64_icelake-server+znver5.tar.xz
      if: ${{ steps.detect-icelake-server-znver5.outcome != 'failure' }}

    - id: detect-znver2
      run: ls BuildAction/znver2/static/SvtAv1EncApp.exe
      continue-on-error: true
    - run: cd BuildAction/znver2/static && tar cJf Windows_x86-64_znver2.tar.xz SvtAv1EncApp.exe
      if: ${{ steps.detect-znver2.outcome != 'failure' }}
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: BuildAction/znver2/static/Windows_x86-64_znver2.tar.xz
      if: ${{ steps.detect-znver2.outcome != 'failure' }}

    - run: ls BuildAction/x86-64-v3+znver2/static/SvtAv1EncApp.exe
    - run: cd BuildAction/x86-64-v3+znver2/static && tar cJf Windows_x86-64_x86-64-v3+znver2.tar.xz SvtAv1EncApp.exe
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: BuildAction/x86-64-v3+znver2/static/Windows_x86-64_x86-64-v3+znver2.tar.xz


  build-windows-arm64:
    needs: [tag, release]
    runs-on: "windows-11-arm"
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - run: git clone https://gitlab.com/AOMediaCodec/SVT-AV1.git --branch ${{ needs.tag.outputs.version }} --single-branch .
      shell: pwsh

    - uses: Akatmks/build-svt-av1@v1
      with:
        dovi-hdr10plus: "false"
        cmakeflags: "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

    - run: ls BuildAction/armv8.7-a+crypto+sm4+sha3+fp16+sve+sve2+oryon-1/static/SvtAv1EncApp.exe
    - run: cd BuildAction/armv8.7-a+crypto+sm4+sha3+fp16+sve+sve2+oryon-1/static && tar cJf Windows_arm64_armv8.7-a+crypto+sm4+sha3+fp16+sve+sve2+oryon-1.tar.xz SvtAv1EncApp.exe
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: BuildAction/armv8.7-a+crypto+sm4+sha3+fp16+sve+sve2+oryon-1/static/Windows_arm64_armv8.7-a+crypto+sm4+sha3+fp16+sve+sve2+oryon-1.tar.xz


  build-linux-x86-64:
    needs: [tag, release]
    runs-on: "ubuntu-latest"
    steps:
    - run: git clone https://gitlab.com/AOMediaCodec/SVT-AV1.git --branch ${{ needs.tag.outputs.version }} --single-branch .

    - uses: Akatmks/build-svt-av1@v1
      with:
        dovi-hdr10plus: "false"
        cmakeflags: "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

    - id: detect-icelake-server-znver5
      run: ls BuildAction/icelake-server+znver5/static/SvtAv1EncApp
      continue-on-error: true
    - run: cd BuildAction/icelake-server+znver5/static && tar cJf Linux_x86-64_icelake-server+znver5.tar.xz SvtAv1EncApp
      if: ${{ steps.detect-icelake-server-znver5.outcome != 'failure' }}
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: BuildAction/icelake-server+znver5/static/Linux_x86-64_icelake-server+znver5.tar.xz
      if: ${{ steps.detect-icelake-server-znver5.outcome != 'failure' }}

    - id: detect-znver2
      run: ls BuildAction/znver2/static/SvtAv1EncApp
      continue-on-error: true
    - run: cd BuildAction/znver2/static && tar cJf Linux_x86-64_znver2.tar.xz SvtAv1EncApp
      if: ${{ steps.detect-znver2.outcome != 'failure' }}
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: BuildAction/znver2/static/Linux_x86-64_znver2.tar.xz
      if: ${{ steps.detect-znver2.outcome != 'failure' }}

    - run: ls BuildAction/x86-64-v3+znver2/static/SvtAv1EncApp
    - run: cd BuildAction/x86-64-v3+znver2/static && tar cJf Linux_x86-64_x86-64-v3+znver2.tar.xz SvtAv1EncApp
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: BuildAction/x86-64-v3+znver2/static/Linux_x86-64_x86-64-v3+znver2.tar.xz


  build-macos-arm64:
    needs: [tag, release]
    runs-on: "macos-latest"
    steps:
    - run: git clone https://gitlab.com/AOMediaCodec/SVT-AV1.git --branch ${{ needs.tag.outputs.version }} --single-branch .

    - uses: Akatmks/build-svt-av1@v1
      with:
        dovi-hdr10plus: "false"
        cmakeflags: "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

    - run: ls BuildAction/armv8.5-a+simd+crypto+apple-m3/static/SvtAv1EncApp
    - run: cd BuildAction/armv8.5-a+simd+crypto+apple-m3/static && tar cJf macOS_arm64_armv8.5-a+simd+crypto+apple-m3.tar.xz SvtAv1EncApp
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: BuildAction/armv8.5-a+simd+crypto+apple-m3/static/macOS_arm64_armv8.5-a+simd+crypto+apple-m3.tar.xz


  build-macos-x86-64:
    needs: [tag, release]
    runs-on: "macos-26-intel"
    steps:
    - run: git clone https://gitlab.com/AOMediaCodec/SVT-AV1.git --branch ${{ needs.tag.outputs.version }} --single-branch .

    - uses: Akatmks/build-svt-av1@v1
      with:
        dovi-hdr10plus: "false"
        cmakeflags: "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

    - run: ls BuildAction/skylake/static/SvtAv1EncApp
    - run: cd BuildAction/skylake/static && tar cJf macOS_x86-64_skylake.tar.xz SvtAv1EncApp
    - uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        files: BuildAction/skylake/static/macOS_x86-64_skylake.tar.xz
